### ISSUE TITLE
[mockAnswer] PopGen

### ISSUE THREAD

**Issue by shouldsee** [compbio-2017/Discussion#14]
<a name='top'></a>
## Contribution
Please add a new comment containing the question decription followed by your answer, and hyper-link it in the following list using [html anchor](https://gist.github.com/asabaylus/3071099#) (don't bother if too complicated) .

### Natural selection

1.  Contrast the definitions of Melthusian fitness and Darwinian fitness. Compare their solutions under a simple selection pressure if you can.
1. Note that simple selection model consider a single loci with two candidate alleles. This is likely to be too simple in real life. State the assumptions behind this model and list common modifications accordingly.
1. What's the role of neutral mutation in selection? How is this related to epistasis? Do you think that effect of mutation is dependent/independent on its geneitc background? Why? 

### Other models

1. What is genetic drift? How does it affect the genotype over time? How would you estimate the drift given a SNP dataset? How is allele fixation different with and without drift?
1. What is epistasis? Is it better to assume additive fitness across loci or epstasis? State the biological motivation of your assumption.
1. Contrast epistasis and recombination as two models for explaining loci-loci interaction. Apply both to predict the temporal evolution of influenza, given its particular genomic organization and means of inheritance. Comment on how evolution of influenza relates to its pathogenecity and how hypotheses can be tested using high-throughput sequencing.

### Inference:

1. What model would you use for inferring the selection strength given allele/haplotype/genotype counts over time?
1. Why could direct measurement of evolution be hard in practice? How is such difficulty addressed in real research? What are the Pros and Cons of different model systems?

### Overall 

1. How can you correlate phenotypic variation to genotypic variation? Give an example and make a quantitative/qualitative argument. 
1. Is the evolution happening on the protein level, mRNA level or DNA level? Give examples accordingly. [answer](#OQ2)

**Comment by shouldsee** [comment]
### Natural selection
1. Darwinian/Malthusian Fitness
![image](https://user-images.githubusercontent.com/8034156/39873279-5bf9588e-5462-11e8-9c77-ae438ca86f6a.png)
![image](https://user-images.githubusercontent.com/8034156/39873271-576c871e-5462-11e8-9ff5-17f08ff44f0f.png)

**Comment by shouldsee** [comment]
<a name="OQ2"></a>

### Is the evolution happening on the protein level, mRNA level or DNA level? Give examples accordingly.

  *A*: Since enzymes/proteins are the major workhorses of biological processes, they are of direct functional importance, as supported by the observation of enriched synonymous mutations in CDS(coding sequence) under a selection pressure. However, in system like influenza viruses and bacteria, it is beneficial to have a smaller genome both for efficient replication and for lower mutation load, where DNA is directed selected for. As for protein evolution, antibiotic resistance is often conferred via mutations in enzymes that cause removal of affinity towards or degradation of antibiotics, which gave the corresponding strains a selective advantage.

[back to top](#top)

**Comment by claudiafeng123** [comment]
Suppose that in a haploid, one locus, 2 allele model, we have the alleles A and a occuring proportions q_A and q_a = 1-q_A, respectively. 

In Malthusian fitness, the q_A evolves according to the continuous time described by

d(q_A)/dt = \sigma q_A (1-q_A)

This implies that q_A(t) evolves according to equation

 q_A(t) = \frac{q_A(0) * e^{\sigma*t}}{1-q_A(0)_q_A(0)e^{\sigma*t}}

In contrast, Darwinian fitness use a discrete time model and is centered the idea of the mean fitness of the population, denoted by 

\overbar{w} = q_{AA}w_{AA} + q_{Aa}w_{Aa} + q_{aa}w_{aa}

Under Darwinian fitness, the mean frequency of AA in the next generation is 

\frac{w_{AA}q_{AA}}{\overbar{w}}

If we consider the evolution of q_A(t) under Malthusian fitness over a single unit of time, we have

q_A(t+1) = \frac{q_A(t) * e^{\sigma}}{1-q_A(t)_q_A(t)e^{\sigma}}

which is equivalent to the mean frequency given by Darwinian fitness assuming that w_A = e^\sigma and w_a = e^0 =1.
