### ISSUE TITLE
Please someone help me /apply/ myself

### ISSUE THREAD

**Issue by danjamesadams** [compbio-2017/Discussion#2]
Howdy team!

So I can't get lapply (or a family variant) to work for what I want to do. I want to use rep(x = column1, times = column2) for each line of a data frame and then concatenate this into a single string.

Say I have a data frame like as follows: 

```{r}
testdf <- data.frame("Letter" = c("A", "B", "C"), "Times" = c("3", "5", "1"))
testdf
```
Letter | Times
------ | -----
A | 3
B | 5
C | 1

Then I want the output as

```{r}
A A A B B B B B C
```

I have it working as a quite messy for loop, but it's not perfect and relies on a break (as the 'times' is always different I have to find the next '0' in a vector to set the entry point for the new data).

```{r} 
vector <- rep(0, times = totaltimes)

for (i in 1:length(dataframe$column1)) {

  if (vector[totaltimes] != 0) break
  
 temp <- min(which(vector == 0))
  
  vector[temp:(temp + dataframe$column2[i])] <- rep(dataframe$column1[i], times = dataframe$column2[i]))
                  
}
```
As you can see this is quite frankly gross, though it does the trick. 

I've tried a ton of different apply things but nothing has worked. I have very little idea how to properly specify which columns I want apply to do what with, so any help would be appreciated muchly!

Cheeeeeeeeeeers.

**Comment by shouldsee** [comment]
1. You probably do not want lapply because it will iterate through each column rather then each row. This can be tested by setting "FUN" to a dummy function like "length"

```{r}
testdf <- data.frame("Letter" = c("A", "B", "C"), "Times" = c("3", "5", "1"))
testdf
lapply(testdf, FUN=length)

# > lapply(testdf, FUN=length)
# $Letter
# [1] 3
# 
# $Times
# [1] 3
```

2. In order to iterate through each row, you will need to use "apply"

The help page `?apply` reads:
> Apply Functions Over Array **Margins**
> 
> Description
> 
> Returns a vector or array or list of values obtained by applying a function to **margins** of an array or matrix.

Let's try dummy function again.
```r
apply(testdf,FUN = length, MARGIN=1)
#[1] 2 2 2
apply(testdf,FUN = length, MARGIN=2)
#Letter  Times 
#     3      3 
```
We should agree that MARGIN=1 is our choice. You can then write a `function(x){rep(x[1],as.integer(x[2]))}`  and plug it into FUN. It's important to write this function with x as a length-2 character vector in mind, but you can always check with functions like `length` or `is`.

At the end, you will need the magic of `unlist(blah)` to recover the result into a vector.

Hope that helps

**Comment by bkompa** [comment]
1. paste(lapply(1:length(df$Letter) function(x) rep(df$Letter[x], df$Times[x]), collapse=" ")

**Comment by danjamesadams** [comment]
When I run those two sets of commands (in order) I get:

```r
apply(testdf, FUN = function(x, y) {rep(x = x, times = y)}, MARGIN=1)
```

(blank)| [,1] | [,2] | [,3]
---| ---- | --- | ---
Letter | "A" | "B" | "C"
Times | "3" | "5" | "1"

and

```r
unlist(lapply(1:length(testdf$Letter), function(x) rep(testdf$Letter[x], testdf$Times[x])))
```

[1] A A B B B C

------
The second one is close to what I'm after but for some reason isn't giving the right numbers?

**Comment by shouldsee** [comment]
@danjamesadams WHAT did you run?

Notice I have updated my answer and we should write function as `function(x){}` rather than `function(x,y){}`, because the input is a vector rather than elements of the vector.
See [here](https://github.com/compbio-2017/Discussion/issues/2#issuecomment-342539956)

**Comment by danjamesadams** [comment]
apply(testdf, FUN = function(x, y) {rep(x = x, times = y)}, MARGIN=1)

and

unlist(lapply(1:length(testdf$Letter), function(x) rep(testdf$Letter[x], testdf$Times[x])))

**Comment by danjamesadams** [comment]
Ah that's amazing, thanks very much both!

**Comment by bkompa** [comment]
Try this: paste(lapply(1:length(testdf$Letter) function(x) rep(testdf$Letter[x], str2num(testdf$Times[x])), collapse=" ")
