### ISSUE TITLE
How to pull data from (vector) iteratively named subsets (WTF?)

### ISSUE THREAD

**Issue by danjamesadams** [compbio-2017/Discussion#7]
So the title isn't clear at all because I really have no idea how to describe this issue without code.

Anyway, I have an object that has several 'attribute layers' (not sure what they're called), such that the following code gives me a single result:

```{r}
A$B[1]$C$D
```
In the above example 'A' is my object, and then B[1] contains C, which contains D. D gives me a final, single result. I have a vector of length > 1 and want to write a piece of code that will extract a list of 'D' values equal to the length of my vector.

I've tried this sort of thing:

```{r}
V1 <- input vector of numbers
V2 <- storage vector of 0s, same length as V1

for (i in 1:length(V1)) {

V2[i] <- A$B[1]$V1[i]$D

}
```
But it only ever gives me NULL. 

If it's relevant, C is numeric, so it's normally it's in those gross '`' characters. For example:
```{r}
A$B[1]$`1000`$D
```

I've tried keeping and getting rid of those, but it doesn't make a difference. 

I'm happy to provide the code I've tried to use and have failed with, but it looks pretty scary because the data I want to extract has different D values for each iteration, so I have to use a big 'A$B$C$D[which(X == 'Y')].

I know it's just the part inside the `s that isn't working because when I manually swap in the numbers it works fine. But I have thousands of these so it's not at all feasible (I know it will take a while anyway, but not as long!)

Any help would be MUCHO* appreciated as I can't really progress past this.

\* I will buy you chocolate or alcohol

**Comment by danjamesadams** [comment]
Happily I found a way around this, but if anyone knows how to do it, it's still interesting.

**Comment by danjamesadams** [comment]
Found a tricksy way, all good.

**Comment by shouldsee** [comment]
Hi Dan,
It would be helpful if you can provide some code that initialises an exemplar object. In general I prefers `df[['colname']]` over `df$colname` because the dollar sign somehow disallows the usage of string as a specifier.

**Comment by shouldsee** [comment]
Generic solution ` A[['B']][1][['V1']][['D']]`
